# Generated by Django 5.1.6 on 2025-02-20 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('isCompleted', models.BooleanField(default=False)),
                ('dateCreated', models.DateTimeField()),
                ('taskgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.taskgroup')),
            ],
        ),
    ]
