# Generated by Django 5.1.6 on 2025-02-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskgroup',
            name='remarks',
            field=models.CharField(default='', max_length=50),
        ),
    ]
