# Generated by Django 5.1.6 on 2025-02-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_taskgroup_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='isDelayed',
            field=models.BooleanField(default=False),
        ),
    ]
