# Generated by Django 5.1.6 on 2025-02-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_task_isdelayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskgroup',
            name='otherRemarks',
            field=models.CharField(default='', max_length=50),
        ),
    ]
