# Generated by Django 5.1.6 on 2025-02-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_taskgroup_otherremarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyNewTable',
            fields=[
                ('custom_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
